#!/usr/bin/env python3
"""Generate edge-case test map files for the Drone-Mapper project.

Map file grammar (all distances in centimetres, dp=0 ג†’ 1 cm cells):
  bounds min_x max_x min_y max_y min_z max_z xy_dp height_dp
  occupied x y z
  # lines starting with # are comments

Drone config reference (test_data/drone_config.txt):
  min_passable_width/length = 30 cm   ג†’ corridors < 30 cm are impassable
  min_passable_height       = 20 cm
  lidar_z_min = 20 cm, lidar_z_max = 120 cm (relative to drone)
  drone typically flies at z = 50 cm

Maps produced (in test_data/maps/):
  1. map_open_room.txt          - Completely empty space (baseline)
  2. map_narrow_corridor.txt    - 40 cm-wide corridor (passable, just above 30 cm)
  3. map_impassable_gap.txt     - Wall with a 20 cm gap (too narrow for drone)
  4. map_enclosed_room.txt      - Sealed 100x100 cm room, interior unreachable
  5. map_pillars.txt            - Scattered column obstacles
  6. map_dead_end.txt           - U-shaped hall with a dead end
  7. map_multi_height.txt       - Low obstacles (only z=0..40) drone can fly over
"""

import os
from typing import Set, Tuple

Cell = Tuple[int, int, int]

OUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'test_data', 'maps')
os.makedirs(OUT_DIR, exist_ok=True)

# Wall heights used: every 10 cm from 0 to 200 (inclusive).
# This ensures the lidar (z_min=20..z_max=120 above drone at z=50
# ג†’ absolute z=70..170) and collision footprint (z=40..60) always hit.
WALL_ZS = list(range(0, 201, 10))


# ---------------------------------------------------------------------------
# Geometry helpers
# ---------------------------------------------------------------------------

def col(x: int, y: int, zs=WALL_ZS) -> Set[Cell]:
    """Single vertical column at (x, y) through all wall heights."""
    return {(x, y, z) for z in zs}


def wall_along_x(y: int, x_start: int, x_end: int, zs=WALL_ZS) -> Set[Cell]:
    """Horizontal wall (constant y) from x_start to x_end inclusive."""
    return {(x, y, z) for x in range(x_start, x_end + 1) for z in zs}


def wall_along_y(x: int, y_start: int, y_end: int, zs=WALL_ZS) -> Set[Cell]:
    """Vertical wall (constant x) from y_start to y_end inclusive."""
    return {(x, y, z) for y in range(y_start, y_end + 1) for z in zs}


def pillar(cx: int, cy: int, r: int = 5, zs=WALL_ZS) -> Set[Cell]:
    """Square pillar of half-width r centred at (cx, cy)."""
    return {
        (x, y, z)
        for x in range(cx - r, cx + r + 1)
        for y in range(cy - r, cy + r + 1)
        for z in zs
    }


# ---------------------------------------------------------------------------
# Writer
# ---------------------------------------------------------------------------

def write_map(
    filename: str,
    bounds: Tuple[int, int, int, int, int, int],
    cells: Set[Cell],
    description: str,
    notes: str = "",
) -> None:
    min_x, max_x, min_y, max_y, min_z, max_z = bounds
    path = os.path.join(OUT_DIR, filename)
    with open(path, 'w') as f:
        f.write(f"# {description}\n")
        if notes:
            for line in notes.strip().splitlines():
                f.write(f"# {line}\n")
        f.write("# Generated by scripts/generate_test_maps.py\n\n")
        f.write(
            f"bounds {min_x} {max_x} {min_y} {max_y} "
            f"{min_z} {max_z} 0 0\n\n"
        )
        if not cells:
            f.write("# No occupied cells ג€” completely empty space\n")
        else:
            for x, y, z in sorted(cells):
                f.write(f"occupied {x} {y} {z}\n")
    print(f"  {filename:35s}  {len(cells):>6} occupied cells")


# ===========================================================================
# Map 1 ג€” Open room
# Scenario : Completely obstacle-free space.
# Edge case : Baseline / sanity check; scorer should see 100 % reachable.
# ===========================================================================
write_map(
    "map_open_room.txt",
    bounds=(0, 500, 0, 500, 0, 200),
    cells=set(),
    description="Open room: completely empty space (baseline exploration test)",
    notes="""
No occupied cells.  All in-bounds cells default to Empty (SimulationState).
Drone can reach every point; expected score = 100 % mapped.
""",
)

# ===========================================================================
# Map 2 ג€” Narrow corridor (passable)
# Scenario : Two parallel walls span the full X range, creating a 40 cm
#            tunnel in Y.  min_passable_width = 30 cm, so 40 cm is tight
#            but legal.
# Edge case : Drone must squeeze through without touching walls.
# ===========================================================================
# Space: X 0ג€“600, Y 0ג€“200. Corridor at Y 81ג€“120 (40 cm gap).
# South wall inner face: Y=80; north wall inner face: Y=121.
narrow_cells: Set[Cell] = set()
narrow_cells |= wall_along_x(80,  0, 600)   # south wall
narrow_cells |= wall_along_x(121, 0, 600)   # north wall

write_map(
    "map_narrow_corridor.txt",
    bounds=(0, 600, 0, 200, 0, 200),
    cells=narrow_cells,
    description="Narrow corridor: 40 cm-wide tunnel (passable, > 30 cm min width)",
    notes="""
Space 600 x 200 cm.
South wall (y=80) and north wall (y=121) span full length.
Passable corridor: y=81..120 (40 cm wide).
Drone must travel the full X length without deviating into walls.
""",
)

# ===========================================================================
# Map 3 ג€” Impassable gap
# Scenario : Same as Map 2 but the gap is only 20 cm ג€” below the 30 cm
#            minimum passable width.  Drone cannot cross.
# Edge case : Algorithm must recognise the gap as a hard boundary and NOT
#             attempt to pass through it.
# ===========================================================================
# Dividing wall at Y=100 with gap at X=240..259 (20 cm gap).
# Drone cannot fit (needs ג‰¥ 30 cm).
impassable_cells: Set[Cell] = set()
impassable_cells |= wall_along_x(100, 0,   239)   # left segment
impassable_cells |= wall_along_x(100, 260, 500)   # right segment
# Gap at x=240..259 is 20 cm ג€” too narrow

write_map(
    "map_impassable_gap.txt",
    bounds=(0, 500, 0, 500, 0, 200),
    cells=impassable_cells,
    description="Impassable gap: wall with 20 cm opening (< 30 cm, drone cannot pass)",
    notes="""
Horizontal wall at y=100 splits the 500 x 500 space into two halves.
Gap at x=240..259 is 20 cm wide (< 30 cm min_passable_width).
Area y=101..500 is unreachable from the drone start (y < 100 side).
Algorithm should stop exploring northward and leave upper half as NotMapped.
""",
)

# ===========================================================================
# Map 4 ג€” Enclosed inaccessible room
# Scenario : A fully sealed 100 x 100 cm box sits inside an open space.
#            No entrance ג†’ interior cells remain NotMapped forever.
# Edge case : Tests that the scorer/algorithm handles cells it can never see.
# ===========================================================================
# Outer space: 500 x 500.
# Sealed box: X 200ג€“300, Y 200ג€“300 (inner cavity X 201ג€“299, Y 201ג€“299).
enclosed_cells: Set[Cell] = set()
# Box perimeter walls (1 cm thick)
enclosed_cells |= wall_along_x(200, 200, 300)   # south wall
enclosed_cells |= wall_along_x(300, 200, 300)   # north wall
enclosed_cells |= wall_along_y(200, 200, 300)   # west wall
enclosed_cells |= wall_along_y(300, 200, 300)   # east wall

write_map(
    "map_enclosed_room.txt",
    bounds=(0, 500, 0, 500, 0, 200),
    cells=enclosed_cells,
    description="Enclosed room: sealed 100x100 cm box, interior permanently inaccessible",
    notes="""
Solid-walled box at x=200..300, y=200..300 (1 cm thick walls).
Interior cavity (x=201..299, y=201..299) has no entrance.
Lidar cannot see inside; drone cannot enter.
Expected: interior cells remain NotMapped; outer space fully explorable.
""",
)

# ===========================================================================
# Map 5 ג€” Pillar maze
# Scenario : Open 500 x 500 cm space scattered with 10 x 10 cm square pillars.
# Edge case : Tests navigation around multiple isolated obstacles and
#             lidar shadow zones (areas hidden behind pillars).
# ===========================================================================
pillar_centers = [
    (100, 100), (100, 400),
    (250, 150), (250, 350),
    (400, 100), (400, 400),
    (175, 250), (325, 250),
    (250, 50),  (250, 450),
]
pillar_cells: Set[Cell] = set()
for cx, cy in pillar_centers:
    pillar_cells |= pillar(cx, cy, r=5)

write_map(
    "map_pillars.txt",
    bounds=(0, 500, 0, 500, 0, 200),
    cells=pillar_cells,
    description="Pillar maze: 10 square columns in an open room",
    notes="""
Ten 10 x 10 cm pillars scattered symmetrically in a 500 x 500 cm space.
Tests lidar shadow detection and path-finding around isolated obstacles.
All areas between pillars are accessible (min gap ג‰¥ 50 cm > 30 cm).
""",
)

# ===========================================================================
# Map 6 ג€” Dead-end corridor (U-shaped hall)
# Scenario : A U-shaped hallway.  One arm ends in a dead end; the drone
#            must navigate in, recognise there is no exit, and back out.
# Edge case : Backtracking / dead-end handling.
# ===========================================================================
# Layout (y increases upward in this diagram):
#
#   0   100  200  300  400  500
#   |    |    |    |    |    |
#   +----+              +----+  y=400
#   |                        |
#   +----+    [dead]  +------+  y=300
#        |            |
#        +------------+          y=200  ג† bottom of inner U
#
# Outer west wall: x=50, y=200..400
# Outer east wall: x=450, y=200..400
# Outer top wall: y=400, x=50..450
# Inner divider: x=200, y=200..350  (creates left arm/dead-end)
# Inner divider: x=300, y=200..350  (creates right arm)
# Bottom of U: y=200, x=200..300 (seals the pocket)
# Entry gaps: left arm  x=51..199, right arm x=301..449  (both at y=200+)
# ג€” drone enters from y < 200 through either side.
#
# Dead end: left pocket   x=51..199,   y=201..399 (no exit northward)
# Through passage: right side x=301..449, y=200..399 leads back out.

dead_end_cells: Set[Cell] = set()
# Outer walls
dead_end_cells |= wall_along_y(50,  200, 400)    # west
dead_end_cells |= wall_along_y(450, 200, 400)    # east
dead_end_cells |= wall_along_x(400, 50, 450)     # top

# Inner dividers (partial height ג€” stop at y=350 to leave top open)
dead_end_cells |= wall_along_y(200, 200, 350)    # left inner wall
dead_end_cells |= wall_along_y(300, 200, 350)    # right inner wall

# Bottom seal of inner pocket
dead_end_cells |= wall_along_x(200, 200, 300)

write_map(
    "map_dead_end.txt",
    bounds=(0, 500, 0, 500, 0, 200),
    cells=dead_end_cells,
    description="Dead-end maze: U-shaped hall with one dead-end arm",
    notes="""
U-shaped hallway centred in the map.
Left arm  (x=51..199,  y=201..399): dead end, no exit northward.
Right arm (x=301..449, y=201..399): connects around the top (y=351..399).
Drone must explore the left dead-end and backtrack without getting stuck.
Entry from south (y < 200) is open on both sides.
""",
)

# ===========================================================================
# Map 7 ג€” Low obstacles (fly-over challenge)
# Scenario : Several low walls (z=0..40 only) that the drone can fly over
#            by ascending (drone min z = 0, typical flight z = 50).
# Edge case : Tests height-aware navigation; walls that block ground travel
#             but not aerial passage.
# ===========================================================================
# Horizontal walls at z=0..40 that would block a ground vehicle but the
# drone can clear at zג‰¥50 (above the 40 cm obstacle top).
LOW_ZS = list(range(0, 41, 10))   # 0, 10, 20, 30, 40

low_cells: Set[Cell] = set()
# Three staggered low walls across the space
low_cells |= wall_along_x(150, 0, 350, zs=LOW_ZS)   # south low wall
low_cells |= wall_along_x(300, 150, 500, zs=LOW_ZS)  # middle low wall
low_cells |= wall_along_x(450, 0, 350, zs=LOW_ZS)   # north low wall

write_map(
    "map_low_obstacles.txt",
    bounds=(0, 500, 0, 500, 0, 200),
    cells=low_cells,
    description="Low obstacles: walls only z=0..40, drone can fly over at z>=50",
    notes="""
Three staggered walls span partial X ranges at y=150, 300, 450.
Walls only exist at z=0..40; drone flying at z>=50 can pass over freely.
Tests that the algorithm correctly distinguishes height layers:
- lidar from z=50 with z_min=20 starts sensing at z=30 ג€” may still see top of wall.
- CollisionDetector at z=50 (footprint z=40..60) would clip wall at z=40.
- Flying at z=60+ clears all walls completely.
""",
)

print("\nAll maps written to test_data/maps/")

